modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Iconify/issues"
[[mods]]
    modId="iconify"
    version="${file.jarVersion}"
    displayName="Iconify"
    logoFile="iconify.png"
    description='''
    TODO
    '''

[[dependencies.iconify]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconify]]
    modId="silentlib"
    mandatory=true
    versionRange="[5,6)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconify]]
    modId="silentgear"
    mandatory=false
    versionRange="[2.7.1,)"
    ordering="NONE"
    side="BOTH"
