modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
    modId="iconify"
    version="${file.jarVersion}"
    displayName="Iconify"
    logoFile="iconify.png"
    description='''
    TODO
    '''

[[dependencies.iconify]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconify]]
    modId="silentgear"
    mandatory=false
    versionRange="[2.6,)"
    ordering="NONE"
    side="BOTH"
